# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - cc-web-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install and Build
        run: |
          # Increase memory limit for Node.js
          export NODE_OPTIONS="--max-old-space-size=4096"
          
          # Install dependencies
          npm install
          cd frontend
          npm install
          
          # Build frontend
          npm run build
          cd ..

      - name: Clean unnecessary files
        run: |
          rm -rf node_modules
          rm -rf frontend/node_modules
          rm -rf .git
          rm -rf frontend/src
          rm -f .env*
          find . -name "node_modules" -type d -prune -exec rm -rf '{}' +
          find . -name "*.log" -type f -delete


      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . \
          -x "*/node_modules/*" \
          -x ".git/*" \
          -x ".env*" \
          -x "*.log" \
          -x "frontend/src/*" \
          -x "frontend/.vite/*" \
          -x "*.md" \
          -x "release.zip"
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_965D7E6D410E460C9FD7914A6DB51FF9 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2B32743DDFED4D24B705176FA6DDFB7D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_62A40FEAD4F8458D8F619DD9670D4576 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cc-web-app'
          slot-name: 'Production'
          package: .
          