name: Build and deploy Node.js app to Azure Web App - cc-web-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install and Build
        run: |
          # Install dependencies
          npm install
          cd frontend
          npm install
          
          # Build frontend
          npm run build
          cd ..

      - name: Clean unnecessary files
        run: |
          rm -rf frontend/node_modules
          rm -rf .git
          rm -rf frontend/.vite
          rm -rf frontend/src
          rm -f .env*

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . \
          -x "*/node_modules/*" \
          -x ".git/*" \
          -x ".env*" \
          -x "*.log" \
          -x "frontend/src/*" \
          -x "frontend/.vite/*" \
          -x "*.md" \
          -x "release.zip"
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Install server dependencies
        run: npm install

      - name: Douwgrade Az.Accounts workaround
        uses: Azure/powershell@v2
        with:
          azPSVersion: latest
          inlineScript: |
            Install-Module -Name Az.Accounts -RequiredVersion 2.19.0 -Force

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cloud-app'
          package: .